name: Main CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Mill
      uses: jodersky/setup-mill@v0.2.2
      with:
        mill-version: 0.8.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Check formatting
      run: mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Setup Yarn
      uses: Borales/actions-yarn@v2.3.0
    - name: Compile
      run: |
        mill server.compile
        mill client.fastOpt
        mill web.vendor
        mill web.sass
    - name: Run unit tests
      run: mill server.test

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
      LSUG_SSL_PASSWORD: ${{ secrets.LSUG_SSL_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - uses: yilinwei/setup-ammonite@master
      with:
        ammonite-version: 2.0.4
        scala-version: 2.13
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Set up Mill
      uses: jodersky/setup-mill@v0.2.2
      with:
        mill-version: 0.8.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Setup up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Deploy HTTP server
      run: |
        mill ci.synth
        mill ci.deploy
        mill ci.reboot
